In [1]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(2, 3))
print("Первая матрица (2×3):")
print(matrix1)

matrix2 = np.random.randint(1, 11, size=(3, 2))
print("\nВторая матрица (3×2):")
print(matrix2)

result = matrix1 @ matrix2  
print("\nРезультат матричного умножения (2×3 × 3×2 = 2×2):")
print(result)

Первая матрица (2×3):
[[3 3 4]
 [6 1 7]]

Вторая матрица (3×2):
[[10 10]
 [ 9  5]
 [ 4  7]]

Результат матричного умножения (2×3 × 3×2 = 2×2):
[[ 73  73]
 [ 97 114]]
