In [1]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 3))

print("Случайная матрица 3×3:")
print(matrix)

det = np.linalg.det(matrix)

if abs(det) != 0:  
    inv_matrix = np.linalg.inv(matrix)
    print("\nОбратная матрица существует:")
    print(inv_matrix)

    prover = matrix @ inv_matrix
    print("\nПроверка: A × A⁻¹ = E (единичная матрица):")
    print(np.round(prover, 2))
else:
    print("\nМатрица вырождена (определитель = 0), обратная матрица не существует!")

Случайная матрица 3×3:
[[8 7 8]
 [9 1 3]
 [3 2 7]]

Обратная матрица существует:
[[-0.004  0.132 -0.052]
 [ 0.216 -0.128 -0.192]
 [-0.06  -0.02   0.22 ]]

Проверка: A × A⁻¹ = E (единичная матрица):
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0. -0.  1.]]
