In [1]:
import numpy as np

matrix1 = np.random.randint(1, 21, size=(3, 3))
matrix2 = np.random.randint(1, 21, size=(3, 3))

print(matrix1)
print(matrix2)

sum_matrix = matrix1 + matrix2
print("\nСумма матриц (A + B):")
print(sum_matrix)

razn_matrix = matrix1 - matrix2
print("\nРазность матриц (A - B):")
print(razn_matrix)

# Вычисляем поэлементное произведение
proizv = matrix1 * matrix2
print("\nПоэлементное произведение (A * B):")
print(proizv)

[[11 15 12]
 [16  1  8]
 [ 6 17 19]]
[[10  3  2]
 [12 14  9]
 [19 18  5]]

Сумма матриц (A + B):
[[21 18 14]
 [28 15 17]
 [25 35 24]]

Разность матриц (A - B):
[[  1  12  10]
 [  4 -13  -1]
 [-13  -1  14]]

Поэлементное произведение (A * B):
[[110  45  24]
 [192  14  72]
 [114 306  95]]
