In [1]:
import numpy as np

ones_matrix = np.eye(4)
print(ones_matrix)

diagonal = [5, 10, 15, 20]
diagonal_matrix = np.diag(diagonal)
print(diagonal_matrix)

sum_ones = np.sum(ones_matrix)
sum_diagonal = np.sum(diagonal_matrix)

print(f"Сумма всех элементов единичной матрицы: {sum_ones}")
print(f"Сумма всех элементов диагональной матрицы: {sum_diagonal}")
print(f"Разница между суммами: {abs(sum_diagonal - sum_ones)}")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма всех элементов единичной матрицы: 4.0
Сумма всех элементов диагональной матрицы: 50
Разница между суммами: 46.0
