In [1]:
import numpy as np

matrix = np.random.randint(1, 51, size=(4, 4))

print("Исходная матрица (4×4):")
print(matrix)

transpon_matrix = matrix.T  
print("\nТранспонированная матрица:")
print(transpon_matrix)

trace = np.trace(matrix)
print(f"\nСлед матрицы (сумма элементов на главной диагонали): {trace}")

Исходная матрица (4×4):
[[ 8 14 30 10]
 [28 36  3 48]
 [ 5 46 50 23]
 [14 29 36 13]]

Транспонированная матрица:
[[ 8 28  5 14]
 [14 36 46 29]
 [30  3 50 36]
 [10 48 23 13]]

След матрицы (сумма элементов на главной диагонали): 107
