In [1]:
import numpy as np

A = np.array([
    [2, 3, -1],
    [4, -1, 2],
    [-3, 5, 4]
])

B = np.array([5, 6, -2])

print("Система линейных уравнений:")
print("2x + 3y - z = 5")
print("4x - y + 2z = 6")
print("-3x + 5y + 4z = -2")

print("Матрица коэффициентов A:")
print(A)
print()
print("Вектор правой части B:")
print(B)
print()

resh = np.linalg.solve(A, B)

print("Решение системы:")
print(f"x = {resh[0]}")
print(f"y = {resh[1]}")
print(f"z = {resh[2]}")

Система линейных уравнений:
2x + 3y - z = 5
4x - y + 2z = 6
-3x + 5y + 4z = -2
Матрица коэффициентов A:
[[ 2  3 -1]
 [ 4 -1  2]
 [-3  5  4]]

Вектор правой части B:
[ 5  6 -2]

Решение системы:
x = 1.6396396396396398
y = 0.5765765765765767
z = 0.009009009009008976
