In [1]:
import numpy as np

mas1 = np.random.randint(0, 51, size=(1, 5))
mas2 = np.random.randint(0, 51, size=(1, 5))

print(mas1)
print(mas2)

mas = np.concatenate((mas1, mas2), axis=0)
print(mas)

split1, split2 = np.vsplit(mas, 2) 

print("Первый разделенный массив")
print(split1)  
print("Второй разделенный массив")
print(split2)

[[10 40 14 36 34]]
[[49 42  4 33 24]]
[[10 40 14 36 34]
 [49 42  4 33 24]]
Первый разделенный массив
[[10 40 14 36 34]]
Второй разделенный массив
[[49 42  4 33 24]]
