In [1]:
import numpy as np

mas = np.random.randint(1, 101, size = 20)
print(mas)
print(mas[mas % 5 == 0])
mas[mas % 5 == 0] = -1
print(mas)

[ 2 46 72 59  1 89 42 94 74 47 65 55 39 22 92 72 65 26 83 38]
[65 55 65]
[ 2 46 72 59  1 89 42 94 74 47 -1 -1 39 22 92 72 -1 26 83 38]
